export const TICKET_CATEGORIES = [
  "ELECTRICAL",
  "PLUMBING",
  "NETWORK",
  "EQUIPMENT",
  "CLEANING",
  "OTHER",
];

export const TICKET_PRIORITIES = ["LOW", "MEDIUM", "HIGH", "CRITICAL"];

export const TICKET_STATUSES = [
  "OPEN",
  "IN_PROGRESS",
  "RESOLVED",
  "CLOSED",
  "REJECTED",
];
